---
- name: Ensure file deletion events are collected
  hosts: all
  become: yes
  tasks:
    - name: Get UID_MIN value
      command: awk '/^UID_MIN/{print $2}' /etc/login.defs
      register: uid_min
      failed_when: uid_min.stdout == ""
      changed_when: false

    - name: Create audit rule to monitor file deletion events
      copy:
        dest: "/etc/audit/rules.d/50-delete.rules"
        content: |
          # Monitor file deletion and renaming by users
          -a always,exit -F arch=b64 -S rename,unlink,unlinkat,renameat -F auid>={{ uid_min.stdout }} -F auid!=unset -F key=delete
          -a always,exit -F arch=b32 -S rename,unlink,unlinkat,renameat -F auid>={{ uid_min.stdout }} -F auid!=unset -F key=delete
      when: uid_min.stdout != ""

    - name: Ensure audit rules are loaded
      command: augenrules --load
      register: augenrules_output
      failed_when: augenrules_output.rc != 0
      notify:
        - Check audit rules

    - name: Ensure audit service is running
      service:
        name: auditd
        state: started
        enabled: yes

  handlers:
    - name: Check audit rules
      command: auditctl -l
      register: auditctl_output

    - name: Print the audit rules output
      debug:
        msg: "{{ auditctl_output.stdout }}"
