---
- name: Configure audit rules for network environment (CIS 5.2.3.5)
  hosts: all
  become: true

  tasks:
    - name: Ensure audit rules are in place
      copy:
        dest: /etc/audit/rules.d/50-cis-network.rules
        content: |
          -a always,exit -F arch=b64 -S sethostname,setdomainname -k system-locale
          -a always,exit -F arch=b32 -S sethostname,setdomainname -k system-locale
          -w /etc/issue -p wa -k system-locale
          -w /etc/issue.net -p wa -k system-locale
          -w /etc/hosts -p wa -k system-locale
          -w /etc/sysconfig/network -p wa -k system-locale
          -w /etc/sysconfig/network-scripts/ -p wa -k system-locale
      notify: Load audit rules

    - name: Check if auditd is in immutable mode
      command: auditctl -s
      register: audit_status
      changed_when: false

    - name: Warn if auditd is in immutable mode
      debug:
        msg: "⚠️ Auditd is in immutable mode. Reboot is required to apply new rules."
      when: audit_status.stdout is search('enabled[^\\n]*2')

    - name: Pause to allow audit rules to apply
      pause:
        seconds: 5

    - name: Check loaded audit rules
      command: auditctl -l
      register: loaded_audit_rules
      changed_when: false

    - name: Fail if /etc/hosts audit rule is missing
      fail:
        msg: "Audit rule for /etc/hosts is missing!"
      when: "'-w /etc/hosts -p wa -k system-locale' not in loaded_audit_rules.stdout"

  handlers:
    - name: Load audit rules
      command: augenrules --load

   
