---
- name: Ensure audit rules are set to immutable mode (CIS 5.2.3.20)
  hosts: all
  become: yes
  vars:
    audit_immutable_file: /etc/audit/rules.d/99-finalize.rules
 
  tasks:
    - name: Backup current audit.rules file
      copy:
        src: /etc/audit/audit.rules
        dest: /etc/audit/audit.rules.bak
        remote_src: yes
      ignore_errors: yes
 
    - name: Remove existing -e line from audit.rules (if any)
      lineinfile:
        path: /etc/audit/audit.rules
        regexp: '^-e\s+2'
        state: absent
      ignore_errors: yes
 
    - name: Remove old immutable rule file (if any)
      file:
        path: "{{ audit_immutable_file }}"
        state: absent
      ignore_errors: yes
 
    - name: Add '-e 2' to make audit rules immutable
      lineinfile:
        path: "{{ audit_immutable_file }}"
        line: "-e 2"
        create: yes
        state: present
        owner: root
        group: root
        mode: '0640'
 
    - name: Load audit rules
      command: augenrules --load
      register: load_result
      failed_when: "'There was an error' in load_result.stderr and 'Rule exists' not in load_result.stderr"
 
    - name: Check if auditd is in immutable mode
      shell: auditctl -s | awk '/^enabled/ { if ($2 == 2) print "yes"; else print "no" }'
      register: reboot_required
 
    - name: Notify if reboot is required
      debug:
        msg: "⚠️ Reboot required to activate immutable audit mode."
      when: reboot_required.stdout == "yes"
