---
- name: "CIS 3.3.10 | Ensure net.ipv4.tcp_syncookies is enabled"
  hosts: all
  become: yes
  vars:
    sysctl_param: "net.ipv4.tcp_syncookies"
    sysctl_value: "1"
    sysctl_file: "/etc/sysctl.d/60-netipv4_sysctl.conf"
    backup_dir: "/var/backups/sysctl_cis"
    checkpoint_file: "/var/log/cis_3.3.10_tcp_syncookies_applied.chk"

  tasks:

    - name: "Check if CIS 3.3.10 has already been applied"
      stat:
        path: "{{ checkpoint_file }}"
      register: checkpoint_stat

    - name: "Create backup directory if not exists"
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0750'

    - name: "Backup sysctl file if exists"
      copy:
        src: "{{ sysctl_file }}"
        dest: "{{ backup_dir }}/60-netipv4_sysctl.conf.bak_{{ ansible_date_time.iso8601 }}"
        remote_src: yes
      when:
        - not checkpoint_stat.stat.exists
        - ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"

    - name: "Ensure net.ipv4.tcp_syncookies is set persistently"
      lineinfile:
        path: "{{ sysctl_file }}"
        line: "{{ sysctl_param }} = {{ sysctl_value }}"
        create: yes
        state: present

    - name: "Apply setting to running kernel"
      sysctl:
        name: "{{ sysctl_param }}"
        value: "{{ sysctl_value }}"
        state: present
        reload: yes

    - name: "Flush IPv4 route cache"
      command: sysctl -w net.ipv4.route.flush=1

    - name: "Create checkpoint file"
      file:
        path: "{{ checkpoint_file }}"
        state: touch
        mode: '0600'

    - name: "Success message"
      debug:
        msg: "CIS 3.3.10 applied: net.ipv4.tcp_syncookies set to 1 and persisted."

