---
- name: Configure and load login/logout audit rules
  hosts: all
  become: true
  tasks:

    - name: Ensure /etc/audit/rules.d directory exists
      file:
        path: /etc/audit/rules.d
        state: directory
        mode: '0755'

    - name: Create 50-login.rules file for login/logout monitoring
      copy:
        dest: "/etc/audit/rules.d/50-login.rules"
        content: |
          -w /var/log/lastlog -p wa -k logins
          -w /var/run/faillock -p wa -k logins
        mode: '0644'

    - name: Load the new login/logout audit rules with augenrules
      command: augenrules --load
      register: augenrules_result
      failed_when: augenrules_result.rc != 0
      changed_when: true

    - name: Check if a reboot is required
      command: auditctl -s
      register: auditctl_status
      changed_when: false
      failed_when: false

    - name: Print if reboot is required
      debug:
        msg: "Reboot required to load rules"
      when: "'enabled = 2' in auditctl_status.stdout"

    - name: Ensure auditd service is running
      service:
        name: auditd
        state: started
        enabled: true
