---
- name: Ensure correct umask settings on production systems
  hosts: all
  become: yes
  vars:
    umask_value: "027"
    backup_dir: "/backup/etc"
  
  tasks:
    # Ensure backup directory exists
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0700'
      
    # Check current umask settings in all files
    - name: Check umask in /etc/profile
      shell: grep -Psiq 'umask\s+(0?[0-7][2-7][0-7]|u=[rwx]{0,3},g=[rx]{0,2},o=[rwx]{0,3})' /etc/profile
      register: umask_profile
      changed_when: false
      failed_when: false
      
    - name: Check umask in /etc/bashrc
      shell: grep -Psiq 'umask\s+(0?[0-7][2-7][0-7]|u=[rwx]{0,3},g=[rx]{0,2},o=[rwx]{0,3})' /etc/bashrc
      register: umask_bashrc
      changed_when: false
      failed_when: false
      
    - name: Check umask in /etc/login.defs
      shell: grep -Psiq 'UMASK\s+(0?[0-7][2-7][0-7]|u=[rwx]{0,3},g=[rx]{0,2},o=[rwx]{0,3})' /etc/login.defs
      register: umask_login_defs
      changed_when: false
      failed_when: false

    # Handle /etc/profile
    - name: Backup /etc/profile
      copy:
        src: /etc/profile
        dest: "{{ backup_dir }}/profile.bak_{{ ansible_date_time.iso8601_basic }}"
        mode: '0600'
      when: umask_profile.rc != 0
      
    # Handle /etc/bashrc
    - name: Backup /etc/bashrc
      copy:
        src: /etc/bashrc
        dest: "{{ backup_dir }}/bashrc.bak_{{ ansible_date_time.iso8601_basic }}"
        mode: '0600'
      when: umask_bashrc.rc != 0
      
    # Handle /etc/login.defs
    - name: Backup /etc/login.defs
      copy:
        src: /etc/login.defs
        dest: "{{ backup_dir }}/login.defs.bak_{{ ansible_date_time.iso8601_basic }}"
        mode: '0600'
      when: umask_login_defs.rc != 0
      
    # Create the systemwide umask file once
    - name: Set umask in /etc/profile.d/50-systemwide_umask.sh
      copy:
        content: "# Set system-wide umask\numask {{ umask_value }}\n"
        dest: /etc/profile.d/50-systemwide_umask.sh
        mode: '0644'
      register: umask_file_created
      
    # Set umask in /etc/login.defs if not set correctly
    - name: Set umask in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^UMASK'
        line: 'UMASK {{ umask_value }}'
        backup: no
      when: umask_login_defs.rc != 0
