---
- name: "CIS 3.3.11 | Ensure IPv6 Router Advertisements are not accepted"
  hosts: all
  become: yes
  vars:
    sysctl_file: "/etc/sysctl.d/60-netipv6_sysctl.conf"
    backup_dir: "/var/backups/sysctl_cis"
    checkpoint_file: "/var/log/cis_3.3.11_ipv6_ra_disabled.chk"
    sysctl_settings:
      - { name: "net.ipv6.conf.all.accept_ra", value: "0" }
      - { name: "net.ipv6.conf.default.accept_ra", value: "0" }

  tasks:

    - name: "Check if CIS 3.3.11 already applied"
      stat:
        path: "{{ checkpoint_file }}"
      register: checkpoint_stat

    - name: "Check if IPv6 is enabled"
      command: sysctl -n net.ipv6.conf.all.disable_ipv6
      register: ipv6_status
      changed_when: false
      failed_when: false

    - name: "Skip if IPv6 is disabled"
      meta: end_play
      when: ipv6_status.stdout | int == 1

    - name: "Create backup directory"
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0750'

    - name: "Backup sysctl config if it exists"
      copy:
        src: "{{ sysctl_file }}"
        dest: "{{ backup_dir }}/60-netipv6_sysctl.conf.bak_{{ ansible_date_time.iso8601 }}"
        remote_src: yes
      when:
        - not checkpoint_stat.stat.exists
        - ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"

    - name: "Persist IPv6 RA sysctl settings"
      lineinfile:
        path: "{{ sysctl_file }}"
        line: "{{ item.name }} = {{ item.value }}"
        create: yes
        state: present
      loop: "{{ sysctl_settings }}"

    - name: "Apply settings to the running kernel"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop: "{{ sysctl_settings }}"

    - name: "Flush IPv6 route cache"
      command: sysctl -w net.ipv6.route.flush=1

    - name: "Create checkpoint"
      file:
        path: "{{ checkpoint_file }}"
        state: touch
        mode: '0600'

    - name: "Show success message"
      debug:
        msg: "CIS 3.3.11 applied: IPv6 router advertisements disabled and persisted."

