---
- name: Secure /etc/cron.d, back it up, and reboot
  hosts: all
  become: yes
  vars:
    ts: "{{ ansible_date_time.iso8601_basic }}"           
    backup_root: "/var/backups/cron_d"
    backup_dir: "{{ backup_root }}/cron_d_{{ ts }}"

  tasks:
    - name: Ensure backup root exists
      file:
        path: "{{ backup_root }}"
        owner: root
        group: root
        mode: "0700"
        state: directory

    - name: Copy /etc/cron.d to timestamped backup dir
      synchronize:
        src: /etc/cron.d/
        dest: "{{ backup_dir }}/"
        recursive: yes
        owner: yes
        group: yes
        perms: yes
      delegate_to: "{{ inventory_hostname }}"
      register: backup_result

    - name: Set correct ownership and mode on /etc/cron.d
      file:
        path: /etc/cron.d
        owner: root
        group: root
        mode: "0700"            
        state: directory

    - name: Reboot host to apply changes
      reboot:
        reboot_timeout: 300
        test_command: uname -a
      when: backup_result is succeeded
