---
- name: Secure cron configurations and ensure correct permissions
  hosts: all
  become: yes
  vars:
    ts: "{{ ansible_date_time.iso8601_basic }}"
    cron_dirs:
      - name: cron.hourly
        path: /etc/cron.hourly
        backup_root: /var/backups/cron_hourly
      - name: cron.daily
        path: /etc/cron.daily
        backup_root: /var/backups/cron_daily
      - name: cron.weekly
        path: /etc/cron.weekly
        backup_root: /var/backups/cron_weekly
      - name: cron.monthly
        path: /etc/cron.monthly
        backup_root: /var/backups/cron_monthly
      - name: cron.d
        path: /etc/cron.d
        backup_root: /var/backups/cron_d

  tasks:
    - name: Backup /etc/crontab with timestamp
      command: cp /etc/crontab /etc/crontab.backup_{{ ts }}
      ignore_errors: yes

    - name: Ensure permissions on /etc/crontab
      file:
        path: /etc/crontab
        owner: root
        group: root
        mode: '0600'
        state: file

    - name: Include task file to handle cron dir backups and permissions
      include_tasks: cron_dir_permissions.yml
      loop: "{{ cron_dirs }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        cron_name: "{{ item.name }}"
        cron_path: "{{ item.path }}"
        cron_backup_root: "{{ item.backup_root }}"
        ts: "{{ ts }}"


