---
- name: Configure and load session initiation audit rules
  hosts: all
  become: true
  tasks:

    - name: Ensure /etc/audit/rules.d directory exists
      file:
        path: /etc/audit/rules.d
        state: directory
        mode: '0755'

    - name: Get UID_MIN value from /etc/login.defs
      command: awk '/^UID_MIN/ {print $2}' /etc/login.defs
      register: uid_min_result
      failed_when: uid_min_result.stdout == ''
      changed_when: false

    - name: Create 50-session.rules file for session initiation monitoring
      copy:
        dest: "/etc/audit/rules.d/50-session.rules"
        content: |
          -w /var/run/utmp -p wa -k session
          -w /var/log/wtmp -p wa -k session
          -w /var/log/btmp -p wa -k session
        mode: '0644'

    - name: Load the new session initiation audit rules with augenrules
      command: augenrules --load
      register: augenrules_result
      failed_when: augenrules_result.rc != 0
      changed_when: true

    - name: Check if a reboot is required
      command: auditctl -s
      register: auditctl_status
      changed_when: false
      failed_when: false

    - name: Print if reboot is required
      debug:
        msg: "Reboot required to load rules"
      when: "'enabled = 2' in auditctl_status.stdout"

    - name: Ensure auditd service is running
      service:
        name: auditd
        state: started
        enabled: true
