---
- name: Ensure correct permissions on /etc/crontab
  hosts: all
  become: yes
  tasks:

    - name: Backup /etc/crontab with a timestamp
      command: cp /etc/crontab /etc/crontab.backup_{{ ansible_date_time.iso8601_basic }}
      register: backup_result
      ignore_errors: yes

    - name: Ensure /etc/crontab has correct ownership and permissions
      file:
        path: /etc/crontab
        owner: root
        group: root
        mode: '0600'
        state: file

    - name: Reboot the system to apply changes
      reboot:
        reboot_timeout: 300
        test_command: uptime
      when: backup_result is success

