---
- name: Ensure audit=1 is set once in GRUB config
  hosts: all
  become: true
  vars:
    grub_file: /etc/default/grub
    backup_suffix: "{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"
    grub_backup_file: "/etc/default/grub.bak.{{ backup_suffix }}"

  tasks:
    - name: Create a timestamped backup of grub file
      copy:
        src: "{{ grub_file }}"
        dest: "{{ grub_backup_file }}"
        remote_src: yes
      register: backup_result

    - name: Read current GRUB_CMDLINE_LINUX line
      command: grep '^GRUB_CMDLINE_LINUX' {{ grub_file }}
      register: grub_cmdline
      changed_when: false
      check_mode: false

    - name: Ensure 'audit=1' is present only once in GRUB_CMDLINE_LINUX
      replace:
        path: "{{ grub_file }}"
        regexp: '^GRUB_CMDLINE_LINUX=.*'
        replace: "{{ grub_cmdline.stdout | regex_replace('audit=1', '') | regex_replace('\"', ' audit=1\"') }}"
      notify: Update grub config
      when: "'audit=1' not in grub_cmdline.stdout or grub_cmdline.stdout | regex_findall('audit=1') | length > 1"

  handlers:
    - name: Update grub config
      command: grub2-mkconfig -o /boot/grub2/grub.cfg

     

 
