---
- name: Ensure audit=1 is set in GRUB config (CIS 5.2.1.2)
  hosts: all
  become: true
  vars:
    grub_config_file: /etc/default/grub
    grub_backup_dir: /etc/default
    timestamp: "{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"
    grub_backup_file: "{{ grub_backup_dir }}/grub.bak.{{ timestamp }}"

  tasks:

    - name: Check if audit=1 is already present in GRUB config
      command: grep -q '\baudit=1\b' {{ grub_config_file }}
      register: audit_check
      ignore_errors: true
      changed_when: false

    - name: Backup GRUB config if audit=1 is not present
      copy:
        src: "{{ grub_config_file }}"
        dest: "{{ grub_backup_file }}"
        remote_src: true
      when: audit_check.rc != 0
      register: grub_backup

    - name: Append audit=1 to GRUB_CMDLINE_LINUX if not present
      lineinfile:
        path: "{{ grub_config_file }}"
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
        line: 'GRUB_CMDLINE_LINUX="\1 audit=1"'
        backrefs: yes
      when: audit_check.rc != 0

    - name: Update grub2 configuration
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: audit_check.rc != 0
      notify: "Show GRUB config update message"

  handlers:
    - name: Show GRUB config update message
      debug:
        msg: "GRUB configuration updated with audit=1. Please reboot for changes to take effect."
