---
- name: Ensure 'audit=1' is set in GRUB and create backup
  hosts: all
  become: yes
  tasks:

    - name: Get current timestamp
      command: date +%Y%m%dT%H%M%S
      register: timestamp
      changed_when: false

    - name: Always create backup of /etc/default/grub with timestamp
      copy:
        src: /etc/default/grub
        dest: "/etc/default/grub.bak.{{ timestamp.stdout }}"
        remote_src: yes
        mode: preserve
      tags: backup

    - name: Read current GRUB_CMDLINE_LINUX value
      shell: "grep ^GRUB_CMDLINE_LINUX /etc/default/grub | cut -d'=' -f2- | tr -d '\"'"
      register: grub_cmdline
      changed_when: false

    - name: Set GRUB_CMDLINE_LINUX line with audit=1 if not present
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="{{ grub_cmdline.stdout | regex_replace("\\baudit=1\\b", "") | trim }} audit=1"'
        backrefs: no
      register: grub_updated

    - name: Regenerate GRUB config if updated
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: grub_updated.changed
      notify: Grub updated

  handlers:
    - name: Grub updated
      debug:
        msg: "GRUB configuration updated and grub.cfg regenerated."
