---
- name: Check for unconfined services and create a backup file
  hosts: localhost
  become: true
  tasks:

    - name: Ensure backup directory exists
      file:
        path: /var/backups/selinux_unconfined
        state: directory
        mode: '0755'

    - name: Get list of unconfined services (if any)
      shell: "ps -eZ | grep unconfined_service_t | awk -F':' '{ print $NF }'"
      register: unconfined_services
      failed_when: false
      changed_when: false

    - name: Generate timestamp
      command: date +%Y%m%d%H%M%S
      register: timestamp
      changed_when: false

    - name: Check if backup file already exists for today's timestamp
      stat:
        path: "/var/backups/selinux_unconfined/unconfined_services_{{ timestamp.stdout }}.txt"
      register: backup_file

    - name: Create timestamped backup file (only if it does not exist)
      copy:
        dest: "/var/backups/selinux_unconfined/unconfined_services_{{ timestamp.stdout }}.txt"
        content: |
          Timestamp: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          {% if unconfined_services.stdout_lines %}
          {% for svc in unconfined_services.stdout_lines | unique | sort %}
          {{ svc }}
          {% endfor %}
          {% else %}
          No unconfined services found.
          {% endif %}
        mode: '0644'
      when: backup_file.stat.exists == false


     
